# Generated by Django 4.1.1 on 2022-10-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Avtobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('video', models.FileField(upload_to='video/%Y/%m/%d/')),
                ('time_create', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time_time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Автобус')),
                ('door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.door', verbose_name='Дверь')),
            ],
            options={
                'verbose_name': 'Автобусы',
                'verbose_name_plural': 'Автобусы',
                'ordering': ['-time_create'],
            },
        ),
    ]
